sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=parity-ethereum

before_script:

script:
  - docker build -t "${DOCKERHUB_USER}/${IMAGE_NAME}:${TRAVIS_BRANCH}" -f scripts/docker/centos-ocean/Dockerfile .

after_script:
  - docker images
  - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
  - docker push "${DOCKERHUB_USER}/${IMAGE_NAME}:${TRAVIS_BRANCH}"
