sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=parity-ethereum

before_script:

script:
  - docker_tag=${TRAVIS_BRANCH//\//-}
  - docker build -t "oceanprotocol/${IMAGE_NAME}:${docker_tag}" -f scripts/docker/centos-ocean/Dockerfile .

after_script:
  - docker images
  - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
  - docker push "oceanprotocol/${IMAGE_NAME}:${docker_tag}"
