sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=parity-ethereum
    - DOCKERHUB_USER=oceanprotocol

before_script:

script:
  - docker build -t "${DOCKERHUB_USER}/${IMAGE_NAME}:${TRAVIS_BRANCH}" -f docker/centos-ocean/Dockerfile .

after_script:
  - docker images
  - docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
  - docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BRANCH}"
